# Generated by Django 3.0.4 on 2020-03-16 07:48

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Изображение')),
                ('numeration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Нумерация')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SportsArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('open_time', models.CharField(max_length=200, verbose_name='Время открытия')),
                ('close_time', models.CharField(max_length=200, verbose_name='Время закрытия')),
                ('phone_1', models.CharField(max_length=13, null=True, verbose_name='Номер телефона владельца (1)')),
                ('phone_2', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона владельца (2)')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_top', models.BooleanField(default=True, verbose_name='Топ')),
                ('image', models.ImageField(upload_to='advertisements/', verbose_name='Изображение')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('latitude', models.CharField(max_length=15, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=15, verbose_name='Долгота')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='Админ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='sports_area.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Спортивная площадка',
                'verbose_name_plural': 'Спортивные площадки',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galleries/', verbose_name='Изображение')),
                ('sports_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='sports_area.SportsArea', verbose_name='Спортивная площадка')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Галерия',
            },
        ),
    ]
