# Generated by Django 3.0.4 on 2020-03-16 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsarea',
            name='close_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='sportsarea',
            name='image',
            field=models.ImageField(upload_to='sports_area/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sportsarea',
            name='open_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='sportsarea',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
    ]
