# Generated by Django 3.0.4 on 2020-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_area', '0002_auto_20200316_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsarea',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='sportsarea',
            name='whats_app_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Ватсапп номер телефона владельца'),
        ),
    ]
