# Generated by Django 3.0.4 on 2020-03-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_area', '0003_auto_20200320_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsarea',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='sportsarea',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
