# Generated by Django 3.0.4 on 2020-03-31 11:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sports_area', '0005_auto_20200331_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsarea',
            name='infrastructure',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='category', chained_model_field='categories', horizontal=True, to='sports_area.Infrastructure', verbose_name='Инфрастрактура'),
        ),
        migrations.AddField(
            model_name='sportsarea',
            name='type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', default=1, on_delete=django.db.models.deletion.CASCADE, to='sports_area.Type', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
