# Generated by Django 3.0.5 on 2020-04-22 07:49

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sports_area', '0007_auto_20200422_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsarea',
            name='infrastructure',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='category', chained_model_field='category', horizontal=True, to='sports_area.Infrastructure', verbose_name='Инфрастрактура'),
        ),
    ]
