# Generated by Django 3.0.5 on 2020-06-20 16:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports_area', '0008_auto_20200422_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата')),
                ('start_time', models.TimeField(default=datetime.datetime.now, verbose_name='Начальное время')),
                ('end_time', models.TimeField(default=datetime.datetime.now, verbose_name='Время окончания')),
                ('status', models.IntegerField(choices=[(0, 'Ожидания'), (1, 'Принятый'), (2, 'законченный')], default=0, verbose_name='Статус')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_admin', to=settings.AUTH_USER_MODEL, verbose_name='Админ')),
                ('sport_area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sports_area.SportsArea')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирования',
                'verbose_name_plural': 'Бронирование',
            },
        ),
    ]
