# Generated by Django 3.0.5 on 2021-05-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текс')),
                ('user_name', models.CharField(max_length=30, verbose_name='Пользователь')),
                ('email', models.CharField(max_length=30, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
