# Generated by Django 3.0.5 on 2021-05-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
